import HeadPhoneStudio3 from '../assets/images/product1.png';
import Cannon80DEOS from '../assets/images/product3.png';
import AppleSmartWatch from '../assets/images/product12.png';
import SecurityCamera from '../assets/images/product16.png';
import AppleIpad3 from '../assets/images/product17.png';
import XiaomiSmartWatch from '../assets/images/product18.png';
import SonyHeadPhone from '../assets/images/product21.png';
import SurfaceLaptop from '../assets/images/product23.png';
import InfraredSecurityCamera from '../assets/images/product24.png';
import TinyWatchDigital from '../assets/images/product25.png';
import JPLSpaceSpeaker from '../assets/images/product27.png';
import RazorLaptop from '../assets/images/product2.png';
import FastImageCanonCamera from '../assets/images/product4.png';
import AppleTVBox from '../assets/images/product7.png';
import AppleMacbookPro from '../assets/images/product8.png';
import MotorolaPhone from '../assets/images/product22.png';
import Speaker from '../assets/images/products11.png';

export const productsData = [
  {
    id: 1,
    name: "Headphone Studio3",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: HeadPhoneStudio3,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 1,
    color: ["red", "blue", "white", "black"],
    amount: 10,
    rating: 2,
    category: ["Accessories", "Audio", "OnSale"],
    status: ["On sale"],
    tags: ["music", "sound", "speaker"],
  },
  {
    id: 2,
    name: "Canon Camera 80EOS",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: Cannon80DEOS,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["blue", "black"],
    amount: 10,
    rating: 3,
    category: ["Camera", "New Arrival"],
    status: ["On sale"],
    tags: ["Camera"],
  },
  {
    id: 3,
    name: "Apple SmartWatch 3 Series",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: AppleSmartWatch,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 4,
    category: ["Watches", "New Arrival"],
    status: [],
    tags: ["Camera"],
  },
  {
    id: 4,
    name: "Security Camera 360Deg",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: SecurityCamera,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Camera", "Featured"],
    status: [],
    tags: ["Camera"],
  },
  {
    id: 5,
    name: "Apple Ipad3 2020",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: AppleIpad3,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Apple", "On sale"],
    status: ["On sale"],
    tags: ["Apple"],
  },
  {
    id: 6,
    name: "Xiaomi SmartWatch Mini 2022",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: XiaomiSmartWatch,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["SmartWatch", "New Arrival"],
    status: ["On sale"],
    tags: ["SmartWatch"],
  },
  {
    id: 7,
    name: "Sony Headphone Three Demension Sound",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: SonyHeadPhone,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 0,
    category: ["Audio", "New Arrival", "Accessories"],
    status: ["On sale"],
    tags: ["SmartWatch"],
  },
  {
    id: 8,
    name: "Microsoft Surface Laptop 3",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: SurfaceLaptop,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["ComputerAndLaptop", "New Arrival",],
    status: ["On sale"],
    tags: ["SmartWatch"],
  },
  {
    id: 9,
    name: "Infared Security Camera",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: InfraredSecurityCamera,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 3,
    category: ["Cameras", "New Arrival",],
    status: ["On sale"],
    tags: ["Cameras"],
  },
  {
    id: 10,
    name: "Modern Digital Watches",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: TinyWatchDigital,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Watches", "New Arrival",],
    status: ["On sale"],
    tags: ["Watches"],
  },
  {
    id: 11,
    name: "JPL Space Speaker 3D",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: JPLSpaceSpeaker,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 2,
    category: ["Watches", "New Arrival",],
    status: ["On sale"],
    tags: ["Watches"],
  },
  {
    id: 12,
    name: "Razor Laptop CoreI9 10800K",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: RazorLaptop,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["ComputorAndLaptop", "New Arrival",],
    status: ["Featured"],
    tags: ["laptop"],
  },
  {
    id: 13,
    name: "Fast Image Canon Camera",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: FastImageCanonCamera,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Camera", "New Arrival",],
    status: ["Featured"],
    tags: ["laptop"],
  },
  {
    id: 14,
    name: "Apple TV Box",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: AppleTVBox,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Apple", "New Arrival",],
    status: ["Featured"],
    tags: ["Apple"],
  },
  {
    id: 15,
    name: "Apple Macbook Pro 2020",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: AppleMacbookPro,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Apple", "New Arrival",],
    status: ["On sale"],
    tags: ["Apple"],
  },
  {
    id: 17,
    name: "Motorola Flip Phone 2022",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: MotorolaPhone,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["SmartPhone", "New Arrival",],
    status: ["On sale"],
    tags: ["SmartPhone"],
  },
  {
    id: 18,
    name: "Best performance Speaker 2022",
    oldPrice: 412.02,
    newPrice: 399.99,
    description: "Nulla finibus massa non maximus rhoncus. Duis ut ligula et nibh dictum eleifend vel non massa. Aliquam molestie, urna at pellentesque vehicula, sem justo condimentum purus, quis sodales dolor urna ut lorem. Aliquam erat volutpat. Sed ac ligula quis lacus consequat fringilla laoreet quis purus.",
    mainImage: Speaker,
    extraImage1: "",
    extraImage2: "",
    extraImage3: "",
    view: 100,
    color: ["black"],
    amount: 10,
    rating: 5,
    category: ["Audio", "New Arrival",],
    status: ["On sale"],
    tags: ["Audio"],
  },
]